### PR TITLE
Portfolio: Skill and About page

### PR DESCRIPTION
**Pull request by Ashe546**
Added skill page and About page

### CODE REVIEW

**Comment by Ashe546** [comment]
added skill and about page and fixed linter eroor

**Comment by Ashe546** [comment]
added skill and about page and fixed linters error

**Comment by Ashe546** [comment]
added skill and about page and fixed linter error

**Review by roshan-bajgain — COMMENTED** [review]
Hi there, 

You made a great effort on this project but I could not proceed ahead because you don't have a descriptive README file So, Kindly update the descriptive README file.

<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>



## Invalid Submission

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Ashe546** [comment]
Added the skill and about page 
Added a descriptive readme file
Correcter some linter error

**Review by rloterh — CHANGES_REQUESTED** [review]
Hi Ashe, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have an appropriate ReadMe.
Kindly note that _ReadMe_ is mostly the first place that visitors of this project's repository will go and therefore it has to be very detailed and professional. Also, it needs to be done well with respect to this capstone project,  which will likely feature on your portfolio. Therefore, kindly ensure to improve upon these aspects of your ReadMe:
- [ ] _Project description_, _how to set up_, _run and test this project_ **should be detailed, clear, and well** organized. please use [this template](https://github.com/microverseinc/readme-template) but remember to customize it to your project.
- [ ] OPTIONAL
The _code_ aspects in each procedure can be quoted with **backticks** to make the code description look cleaner.
- [ ] Include necessary screenshots, project demo links where applicable so as to give a birds-eye view of your project
- [ ] OPTIONAL
Kindly ensure that your ReadMe is _typo-free_. You can crosscheck by installing the [Grammarly plugin](https://www.grammarly.com/)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Pull request closed without merging**
